### ISSUE TITLE
索尼z5下点击patch按钮直接退出，没有log没有erro提示框

### ISSUE THREAD

**Issue by onlike** [coolspan/Android-Increment-Update#1]
问题已经解决，原因是用了6.0的系统运行但是没有申请6.0的**sd卡读写权限** 导致异常退出
另外，有个地方可以优化下 即安装完毕后调用安装时改为 ：       
        File file = new File(apkPath);
        Intent intent = new Intent();
        intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
        intent.setAction(Intent.ACTION_VIEW);
        String type = "application/vnd.android.package-archive";
        intent.setDataAndType(Uri.fromFile(file), type);
        context.startActivity(intent);
比较好，目前用的安装方式有的机型上不弹出安装成功窗口

**Comment by coolspan** [comment]
Ok
